version: '3'

services:
  whisper-back-end:
    container_name: whisper-api
    build:
      context: .
      dockerfile: dockerFile

    # volumes:
    #   - .:/api
    #   - /api/node_modules

    ports:
      - 8080:8080

    env_file:
      - .env

    # exemplary environment variable for database connection
    # environment:
    #   - DATABASE_URL: "postgresql://USER:PASSWORD@HOST:5432/DB_NAME"
